In [1]:
import numpy as np

In [17]:
np.ndarray?

In [4]:
np.array?

In [19]:
do = np.array([[1,2],[3,4],[5,6]])

In [20]:
do

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
type(do), do.shape, do.size, do.ndim, do.dtype, do.nbytes

(numpy.ndarray, (3, 2), 6, 2, dtype('int32'), 24)

In [31]:
ao = np.arange(10000)

In [29]:
np.linspace?

In [32]:
time0 = %timeit -o [a1 **2 for a1 in ao]

14.4 ms ± 2.4 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [35]:
time1 = %timeit -o ao**2

34.4 µs ± 183 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [36]:
3**2

9

In [37]:
time0.best/time1.best

353.2011488753376

In [38]:
np.ndarray((3,2))

array([[3.47739925e-081, 4.19796317e+175],
       [6.59619323e-042, 2.25409854e+184],
       [5.49156776e+170, 1.05700260e-307]])

In [40]:
np.logspace?

In [45]:
a = np.array([1,3], dtype=np.int64)

In [47]:
a.dtype

dtype('int64')

In [50]:
a.nbytes*8

128

In [49]:
a

array([1, 3], dtype=int64)

In [52]:
a = a + 0.3

In [54]:
a, a.dtype

(array([1.3, 3.3]), dtype('float64'))

In [55]:
a[0] = 2.5

In [56]:
a

array([2.5, 3.3])

In [60]:
np.sqrt([-2,9], dtype=np.complex)

array([0.+1.41421356j, 3.+0.j        ])

In [63]:
np.sqrt?

In [100]:
a = np.arange(8)

In [101]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [102]:
a = a.reshape(2,4)

In [103]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [104]:
a.strides, a.dtype

((16, 4), dtype('int32'))

In [115]:
b = np.random.rand(3, 3)

In [119]:
b.strides

(24, 8)

In [118]:
b, b.dtype

(array([[0.64951111, 0.62220166, 0.99686452],
        [0.47519219, 0.57192851, 0.70941554],
        [0.10413732, 0.52509655, 0.35982141]]), dtype('float64'))

In [121]:
b.strides

(24, 8)

In [124]:
b.transpose()

array([[0.64951111, 0.47519219, 0.10413732],
       [0.62220166, 0.57192851, 0.52509655],
       [0.99686452, 0.70941554, 0.35982141]])

In [126]:
b.reshape(1,9)

array([[0.64951111, 0.62220166, 0.99686452, 0.47519219, 0.57192851,
        0.70941554, 0.10413732, 0.52509655, 0.35982141]])

In [131]:
c = np.ndarray((2,3))

In [137]:
c.shape

(2, 3)

In [141]:
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [142]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [147]:
np.random.random?

In [155]:
np.tril(np.arange(9).reshape(3,-1), -1)

array([[0, 0, 0],
       [3, 0, 0],
       [6, 7, 0]])

In [153]:
np.tril?

In [156]:
np.savetxt?

In [157]:
[[i+j for j in range(6)] for i in range(0,60,10)]

[[0, 1, 2, 3, 4, 5],
 [10, 11, 12, 13, 14, 15],
 [20, 21, 22, 23, 24, 25],
 [30, 31, 32, 33, 34, 35],
 [40, 41, 42, 43, 44, 45],
 [50, 51, 52, 53, 54, 55]]

In [164]:
x = np.array([[1,2,5],[3,4,6]])

In [168]:
np.repeat(x, [3,4], axis=0)

array([[1, 2, 5],
       [1, 2, 5],
       [1, 2, 5],
       [3, 4, 6],
       [3, 4, 6],
       [3, 4, 6],
       [3, 4, 6]])

In [169]:
a = np.arange(10)

In [175]:
b=a[::2]

In [177]:
b1=a[5:]

In [179]:
c=a.copy()

In [181]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [194]:
np.may_share_memory(a,b1)

True

In [195]:
np.may_share_memory?

In [198]:
b1.base is a

True

In [197]:
c.base is a

False

In [201]:
c = a.flatten()

In [202]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [211]:
a  = np.random.rand(5, 3)
a

array([[0.95992033, 0.52310209, 0.65617823],
       [0.64332776, 0.51383704, 0.43715563],
       [0.5555748 , 0.01086255, 0.4542758 ],
       [0.59304748, 0.46893894, 0.04148043],
       [0.6691401 , 0.27485307, 0.26830693]])

In [209]:
c = a.flatten()

In [210]:
c

array([0.96325471, 0.31874008, 0.42121656, 0.47503257, 0.47207804,
       0.93460342, 0.65140603, 0.61858218, 0.03352573, 0.84761407,
       0.02967438, 0.72596146, 0.523989  , 0.18671868, 0.21306965])

In [214]:
flatten?

SyntaxError: invalid syntax (<ipython-input-214-075fbb1806a5>, line 1)

In [215]:
a = np.random.rand(10, 9, 7)

In [216]:
a

array([[[3.18882686e-03, 2.35636397e-01, 9.46800983e-01, 6.68828010e-01,
         8.20105289e-01, 2.85738367e-01, 7.38728583e-01],
        [5.92621448e-02, 9.39365485e-01, 4.06126664e-01, 4.85696350e-01,
         1.63135603e-01, 7.75456209e-01, 2.77878208e-01],
        [5.67697137e-01, 1.06212186e-01, 5.38871263e-01, 6.63500501e-01,
         4.58328870e-01, 4.77093502e-01, 5.79331148e-01],
        [8.74701815e-01, 7.98866264e-01, 9.70824473e-01, 2.85852851e-01,
         8.33767455e-01, 3.99771147e-01, 5.92117975e-01],
        [3.81941286e-01, 3.80006193e-01, 8.49104706e-01, 2.90059676e-01,
         8.30968085e-01, 7.49359947e-01, 5.94364773e-01],
        [9.76620328e-01, 3.63337338e-01, 8.04803749e-01, 5.12498942e-01,
         8.13445864e-01, 2.09816217e-01, 6.54609215e-01],
        [9.49729704e-01, 4.98086914e-01, 4.75764860e-01, 9.36643445e-01,
         7.17651178e-01, 9.31357342e-02, 8.05631789e-01],
        [1.57186867e-02, 8.28725399e-01, 8.62434582e-01, 9.35814762e-01,
         9

In [223]:
a = np.random.rand(10)

In [224]:
a

array([0.39837026, 0.30821851, 0.608576  , 0.98448765, 0.43816189,
       0.73893848, 0.18516939, 0.73326884, 0.71617969, 0.46119525])

In [230]:
a[a>0.5]

array([0.608576  , 0.98448765, 0.73893848, 0.73326884, 0.71617969])

In [231]:
np.where(a>0.5)

(array([2, 3, 5, 7, 8], dtype=int32),)

In [232]:
a[np.sin(a)>0.2]

array([0.39837026, 0.30821851, 0.608576  , 0.98448765, 0.43816189,
       0.73893848, 0.73326884, 0.71617969, 0.46119525])

In [237]:
np.select((a<0.3,a>0.8), (a, a*2))

array([0.        , 0.        , 0.        , 1.96897529, 0.        ,
       0.        , 0.18516939, 0.        , 0.        , 0.        ])

In [235]:
a

array([0.39837026, 0.30821851, 0.608576  , 0.98448765, 0.43816189,
       0.73893848, 0.18516939, 0.73326884, 0.71617969, 0.46119525])

In [245]:
np.tril(np.random.random((3,3)))

array([[0.42581857, 0.        , 0.        ],
       [0.48178625, 0.29548845, 0.        ],
       [0.44503701, 0.25088665, 0.24714699]])

In [244]:
np.random.random((3,3))

array([[0.74861983, 0.80566896, 0.25112146],
       [0.0817347 , 0.24395081, 0.12691199],
       [0.48586112, 0.87695124, 0.67615923]])

In [247]:
np.arange(0,40,10)

array([ 0, 10, 20, 30])

In [249]:
np.repeat?

In [252]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T

In [253]:
b = np.array([0, 1, 2])

In [255]:
c = np.empty_like(a)

In [258]:
np.empty?

In [263]:
a.shape[1]

3